version: "2"

services:
  mountebank:
    image: wzulfikar/mbwatch
    volumes:
      - ./mountebank:/mountebank
    command: --configfile mountebank/imposter.ejs --port 2525 --logfile mountebank/mb.log
    ports:
      - 8001:8001
      - 8002:8002
